# 1. Samples were taken from a distribution, and the histogram of those samples is shown here:
# 
#      400 |          _
#      350 |         / \
#      300 |        /   \
#      250 |       /     \
#      200 |      /       \
#      150 |     /         \
#      100 |    /           \
#       50 |  _/             \_
#        0 |_____________________
#           -2    0    2    4    6
# 
# Which of the following distributions were the samples taken from?
# [ ] Uniform Distribution
# [ ] Exponential Distribution
# [X] Normal Distribution

# ---------------------------------------------------------

# 2. Which of the following histograms best matches samples taken from 
#    a uniform distribution between 0 and 2?
# 
#    Figure 2 (Selected Answer):
#      600 |
#      500 |
#      400 |
#      300 |
#      200 |  _________________
#      100 |  |               |
#        0 |__|_______________|__
#            0.0    1.0    2.0
# 
# [ ] Figure 1 (Normal)
# [X] Figure 2 (Uniform 0 to 2)
# [ ] Figure 3 (Uniform 0 to 1)
# [ ] Figure 4 (Exponential)

# ---------------------------------------------------------

# 3. Each of the following histograms was generated by sampling a different 
#    normal distribution. Which histogram best matches the normal distribution 
#    with the highest variance of the three?
# 
#    Figure 3 (Selected Answer - Widest Spread):
#      700 |
#      600 |
#      500 |
#      400 |
#      300 |
#      200 |        _______
#      100 |    ___/       \___
#        0 |___/               \___
#            -4  -2   0   2   4
# 
# [ ] Figure 1 (Low Variance / Skinny)
# [ ] Figure 2 (Medium Variance)
# [X] Figure 3 (High Variance / Wide)

# ---------------------------------------------------------

# 4. Mary's Clothes Shoppe is a moderately busy store. Which of the following 
#    histograms best matches observations of how much time (in minutes) there 
#    is between customer arrivals?
# 
#    Figure 1 (Selected Answer - Exponential Distribution):
#      400 | \
#      350 |  \
#      300 |   \
#      250 |    \
#      200 |     \
#      150 |      \
#      100 |       \
#       50 |        \________
#        0 |__________________
#            0   5   10  15  20
# 
# [X] Figure 1 (Exponential)
# [ ] Figure 2 (Normal)
# [ ] Figure 3 (Uniform)
